/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\0_MoonSea\Shader\ShipParticle_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform sampler2D _BufferA;"
 "uniform float _MoveStartTime,_MoveTimeDuration;"
 "vec3 f;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "#define dmin 0.001\n"
 "#define tmax 1000.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\nstruct mapr{float d;bool hit;int m;float i;float tvalue;float acc;};"
 "void n(inout mapr v,float d,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,f,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,f,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 s(vec3 v,vec3 d,vec3 f,vec3 n)"
 "{"
   "return v+=n,v.yz*=rot(d.x),v.xz*=rot(d.y),v.xy*=rot(d.z),v*=d,v;"
 "}"
 "vec2 n(float v)"
 "{"
   "float d=sin(v*.11),f=cos(v*.14);"
   "return vec2(d*4.-f*1.5,f*1.7+d*1.5);"
 "}"
 "float s(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "float n(vec3 v,vec3 d)"
 "{"
   "return length(max(vec3(0.),abs(v)-d));"
 "}"
 "mapr v(vec3 v)"
 "{"
   "mapr d=mapr(1e3,false,-1,0.,0.,0.);"
   "for(float e=0.;e<20.;e++)"
     "{"
       "float a=.25+s(vec2(99.99,4545.21)*e)*1.25,y=s(vec2(6.621,1.11148)*e)*2.*3.1415,x=s(vec2(1.9987,.2259)*e)*2.*3.1415;"
       "vec3 t=vec3(a*cos(_time+y)*cos(_time+x),a*cos(_time+y)*sin(_time+x),a*sin(_time+y));"
       "n(d,length(v+t+f)-.001,0,true);"
     "}"
   "return d;"
 "}"
 "vec3 t(vec3 d)"
 "{"
   "vec2 f=vec2(.001,0.);"
   "return normalize(vec3(v(d+f.xyy).d-v(d-f.xyy).d,v(d+f.yxy).d-v(d-f.yxy).d,v(d+f.yyx).d-v(d-f.yyx).d));"
 "}"
 "mapr n(vec3 d,vec3 f,float e)"
 "{"
   "mapr m;"
   "float t=0.,a=0.,n=0.;"
   "for(;++t<e;)"
     "{"
       "m=v(d+f*(a+=m.d));"
       "if(m.d<dmin||m.tvalue>tmax)"
         "break;"
       "n+=exp(-15.*m.d);"
     "}"
   "m.i=t;"
   "m.tvalue=a;"
   "m.acc=n;"
   "return m;"
 "}"
 "vec4 t(mapr v,vec3 d,vec3 f,vec2 e)"
 "{"
   "vec4 t=vec4(vec3(.125,.291,.723)*v.acc*8.,1.);"
   "return t;"
 "}"
 "void main()"
 "{"
   "vec2 v=uv*2.-1.;"
   "v.x*=_resolution.x/_resolution.y;"
   "vec3 d=vec3(cos(_time),0.,sin(_time)),a=vec3(0.,0.,0.),e=normalize(a-d),y=normalize(cross(vec3(0.,1.,0.),e)),s=normalize(cross(e,y)),i=normalize(v.x*y+v.y*s+e);"
   "float m=clamp((_time-_MoveStartTime)/_MoveTimeDuration,0.,1.);"
   "f=vec3(0.,sin(m*2.*pi)*.5-.5,0.);"
   "mapr c=n(d,i,64.);"
   "vec4 r=t(c,d,i,v),x=texture(_BufferA,uv);"
   "r=mix(r,x,.981);"
   "gl_FragColor=r;"
 "}",

