/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\5_ChangeOfMind\Shader\NegativeSphere_Frag.h
"#version 330\n"
 "#extension GL_ARB_separate_shader_objects:enable\n"
 "layout(location=0) in vec2 in_uv;"
 "layout(location=1) in vec4 in_WorldVertexPos;"
 "layout(location=2) in vec4 in_WorldNormal;"
 "layout(location=3) flat in float in_Displacement;"
 "layout(location=4) in vec4 in_AnchorPos;"
 "uniform int _UseColor;"
 "uniform vec4 _Color;"
 "uniform int _UseLighting;"
 "uniform vec3 _LightDir,_LightPos,_WorldCameraPos;"
 "uniform int _UseEnvColor;"
 "uniform vec4 _EnvColor;"
 "uniform int _UseMainTex;"
 "uniform sampler2D _MainTex;"
 "uniform int _UseMainCube;"
 "uniform samplerCube _MainCube;"
 "uniform float _Alpha;"
 "void main()"
 "{"
   "vec4 i=vec4(vec3(0.),1.);"
   "if(_UseColor==1)"
     "i=_Color;"
   "else"
     " if(_UseMainTex==1)"
       "i=texture(_MainTex,in_uv);"
     "else"
       " if(_UseMainCube==1)"
         "{"
           "vec3 v=-normalize(_WorldCameraPos-in_WorldVertexPos.xyz),n=normalize(reflect(v,in_WorldNormal.xyz));"
           "i.xyz=texture(_MainCube,n).xyz;"
         "}"
       "else"
         " i=vec4(1.);"
   "vec4 v=vec4(0.,0.,0.,1.);"
   "if(_UseEnvColor==1)"
     "v=_EnvColor;"
   "if(_UseLighting==1)"
     "{"
       "vec3 n=normalize(_LightPos-in_WorldVertexPos.xyz);"
       "float r=max(0.,dot(in_WorldNormal.xyz,n));"
       "i.xyz*=r;"
       "i.xyz+=v.xyz;"
       "vec3 l=-1.*normalize(in_WorldVertexPos.xyz-_WorldCameraPos),z=normalize(l+n);"
       "float u=pow(max(0.,dot(in_WorldNormal.xyz,z)),60.);"
       "u=min(1.,u);"
       "i.xyz+=vec3(1.)*u;"
     "}"
   "float n=distance(in_WorldVertexPos.xyz,in_AnchorPos.xyz)/1.5;"
   "i=mix(i,vec4(3.,0.,0.,1.),clamp(n,0.,1.));"
   "i.w*=_Alpha;"
   "gl_FragColor=i;"
 "}",

