/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\Art_ReReRe\Haru86_GraphicsEngine\GraphicsEngine\Graphics\Shader\Standard_Frag.h
"#version 430\n"
 "#extension GL_ARB_separate_shader_objects:enable\n"
 "layout(location=0) in vec2 in_uv;"
 "layout(location=1) in vec4 in_WorldVertexPos;"
 "layout(location=2) in vec4 in_WorldNormal;"
 "layout(location=3) flat in int in_gl_InstanceID;"
 "layout(location=4) in vec4 in_Color;"
 "out vec4 out_Color;"
 "uniform int _UseColor;"
 "uniform vec4 _Color;"
 "uniform int _Use2FColor,_UseLighting;"
 "uniform vec3 _LightDir,_LightPos,_WorldCameraPos;"
 "uniform int _UseEnvColor;"
 "uniform vec4 _EnvColor;"
 "uniform int _UseMainTex,_UseMainEditorTex;"
 "uniform sampler2D _MainTex;"
 "uniform int _UseMainCube;"
 "uniform samplerCube _MainCube;"
 "uniform int _UseRim,_IsRimMul;"
 "uniform vec4 _RimColor;"
 "uniform float _RimPower,_RimMulVal,_EditorOffset,_ShrinkRate,_FontSize,_wCharH;"
 "void main()"
 "{"
   "vec4 i=vec4(vec3(0.),1.),v=vec4(0.,0.,0.,1.);"
   "if(_UseEnvColor==1)"
     "v=_EnvColor;"
   "if(_UseColor==1)"
     "i=_Color;"
   "else"
     " if(_Use2FColor==1)"
       "i=in_Color,v=in_Color;"
     "else"
       " if(_UseMainTex==1)"
         "{"
           "vec4 n=texture(_MainTex,vec2(in_uv.x,1.-in_uv.y));"
           "i=_Color*n.x;"
         "}"
       "else"
         " if(_UseMainEditorTex==1)"
           "{"
             "vec2 l=vec2(in_uv.x,in_uv.y);"
             "l.y+=-1.;"
             "l*=_ShrinkRate;"
             "l.y+=1.;"
             "vec4 r=texture(_MainTex,vec2(l.x,l.y+_EditorOffset));"
             "i=r;"
             "float n=(_wCharH-1.)*_ShrinkRate+1.,t=.02*_ShrinkRate;"
             "if(l.y<n&&l.x>=t)"
               "i.w=0.;"
           "}"
         "else"
           " if(_UseMainCube==1)"
             "{"
               "vec3 r=-normalize(_WorldCameraPos-in_WorldVertexPos.xyz),n=normalize(reflect(r,in_WorldNormal.xyz));"
               "i.xyz=texture(_MainCube,n).xyz;"
             "}"
           "else"
             " i=vec4(1.);"
   "if(_UseLighting==1)"
     "{"
       "vec3 n=_LightDir;"
       "float r=max(0.,dot(in_WorldNormal.xyz,n));"
       "i.xyz*=r;"
       "i.xyz+=v.xyz;"
       "vec3 l=-1.*normalize(in_WorldVertexPos.xyz-_WorldCameraPos),t=normalize(l+n);"
       "float u=pow(max(0.,dot(in_WorldNormal.xyz,t)),60.);"
       "u=min(1.,u);"
       "i.xyz+=vec3(1.)*u;"
     "}"
   "if(_UseRim==1)"
     "{"
       "vec3 n=-normalize(in_WorldVertexPos.xyz-_WorldCameraPos);"
       "float r=1.-dot(in_WorldNormal.xyz,n);"
       "r=pow(r,_RimPower);"
       "r=max(0.,r);"
       "r*=_RimMulVal;"
       "if(_IsRimMul==1)"
         "i*=_RimColor*r;"
       "else"
         " i=_RimColor*r;"
     "}"
   "if(i.w==0.)"
     "discard;"
   "out_Color=i;"
 "}",

