/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\2_EarthAndMoon\Shader\EarthAndMoon_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter;"
 "uniform float _MoveVal;"
 "in vec2 uv;struct mapr{float d;int m;};"
 "void f(inout mapr m,float v,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(v<m.d)"
         "m=mapr(v,f);"
     "}"
   "else"
     " if(v>m.d)"
       "m=mapr(v,f);"
 "}\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "float f(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "float s(vec2 v)"
 "{"
   "vec2 m=floor(v),x=fract(v);"
   "float a=f(m+vec2(0.,0.)),d=f(m+vec2(1.,0.)),t=f(m+vec2(0.,1.)),c=f(m+vec2(1.,1.));"
   "vec2 s=x*x*(3.-2.*x);"
   "return mix(a,d,s.x)+(t-a)*s.y*(1.-s.x)+(c-d)*s.x*s.y;"
 "}"
 "float v(float v)"
 "{"
   "return fract(sin(v)*753.5453123);"
 "}"
 "float t(vec3 m)"
 "{"
   "vec3 s=floor(m),f=fract(m);"
   "f=f*f*(3.-2.*f);"
   "float a=s.x+s.y*157.+113.*s.z;"
   "return mix(mix(mix(v(a),v(a+1.),f.x),mix(v(a+157.),v(a+158.),f.x),f.y),mix(mix(v(a+113.),v(a+114.),f.x),mix(v(a+270.),v(a+271.),f.x),f.y),f.z);"
 "}"
 "float n(vec2 v)"
 "{"
   "mat2 m=rot(35.6*pi/180.);"
   "float f=0.,a=0.;"
   "for(float d=0.;d<4.;d++)"
     "{"
       "float r=pow(.5,d+1.);"
       "f+=r*s(v);"
       "v=2.*m*v;"
       "a+=r;"
     "}"
   "return f/a;"
 "}"
 "float f(vec3 v,float m,float f)"
 "{"
   "float a=0.,d=0.;"
   "for(float r=0.;r<m;r++)"
     "{"
       "float n=pow(.5,r+1.)*f;"
       "a+=n*t(v);"
       "v=2.*v;"
       "d+=n;"
     "}"
   "return a/d;"
 "}"
 "vec3 n(vec3 v,vec3 m,vec3 f,vec3 a)"
 "{"
   "return v+=a,v.yz*=rot(m.x),v.xz*=rot(m.y),v.xy*=rot(m.z),v*=m,v;"
 "}"
 "mapr m(vec3 v)"
 "{"
   "mapr m;"
   "m.d=1e3;"
   "m.m=-1;"
   "f(m,length(n(v,vec3(1.),vec3(0.),vec3(0.)))-1.,0,true);"
   "{"
     "float a=3.5;"
     "f(m,length(n(v,vec3(1.),vec3(0.),vec3(a*cos(5.451),.8075,a*sin(5.451))))-.5,1,true);"
   "}"
   "return m;"
 "}\n"
 "#define tile 0.850\n"
 "vec3 f(vec3 v,vec3 m)"
 "{"
   "vec3 f=vec3(0.);"
   "float a=.1,s=1.;"
   "v.x+=1.;"
   "for(int r=0;r<20;r++)"
     "{"
       "vec3 d=v+m*a;"
       "float x=0.,n=0.;"
       "d=abs(vec3(tile)-mod(d,vec3(tile*2.)));"
       "for(int i=0;i<17;i++)"
         "{"
           "float t=2.;"
           "d=abs(d)/dot(d,d)*t-.5*t;"
           "n+=abs(length(d)-x);"
           "x=length(d);"
         "}"
       "n*=n*n;"
       "f+=vec3(a,a*a,a*a*a*a)*n*.0015*s;"
       "s*=.73;"
       "a+=.1;"
     "}"
   "return f*.01;"
 "}\n"
 "#define dmin 0.001\n"
 "#define ln 64.0\n"
 "#define ldir normalize(vec3(1.0,1.0,0.85))\n"
 "vec3 r(vec3 v)"
 "{"
   "vec2 f=vec2(dmin,0.);"
   "return normalize(vec3(m(v+f.xyy).d-m(v-f.xyy).d,m(v+f.yxy).d-m(v-f.yxy).d,m(v+f.yyx).d-m(v-f.yyx).d));"
 "}"
 "void main()"
 "{"
   "if(_RenderingTarget==2)"
     "gl_FragColor=vec4(vec3(0.),1.);"
   "else"
     "{"
       "vec2 v=uv*2.-1.;"
       "v.x*=_resolution.x/_resolution.y;"
       "float a=.75,d=.25,s=.95,x=-1.1+_MoveVal;"
       "vec3 i=vec3(0.),n=vec3(a*cos(1.71+x),s,a*sin(1.71+x)),t=vec3(a*cos(1.71+d+x),.85*s,a*sin(1.71+d+x)),y=normalize(t-n),c=normalize(cross(vec3(0.,1.,0.),y)),l=normalize(cross(y,c)),e=normalize(v.x*c+v.y*l+y);"
       "float u=0.,p=0.,z=0.;"
       "mapr k;"
       "for(;++u<ln;)"
         "{"
           "k=m(n+e*(p+=k.d));"
           "if(k.d<dmin)"
             "break;"
           "z+=exp(-3.*k.d);"
         "}"
       "i=f(n,e);"
       "vec3 o=pow(vec3(1.),vec3(2.2));"
       "i+=o*(k.d<dmin?1.:z)*.02;"
       "if(k.m==0)"
         "{"
           "vec3 g=n+e*p;"
           "const mat3 C=mat3(0.,.8,.6,-.8,.36,-.48,-.6,-.48,.64);"
           "vec3 w=g;"
           "w=C*w*2.01;"
           "{"
             "float b=f(2.*w+vec3(160.,40.,120.),6.,1.);"
             "b=pow(b,1.5);"
             "float h=min(4.*max(b-.3,0.),1.);"
             "vec3 W=vec3(1.,1.3,.5);"
             "float V=f(5.*w+vec3(120.),6.,1.);"
             "vec3 T=vec3(0.,.031,.11);"
             "i=mix(T,V*W,h);"
           "}"
           "{"
             "float b=f(7.5*w+vec3(500)+_time,6.,1.);"
             "b=pow(b,1.5);"
             "float h=min(4.*max(b-.3,0.),1.);"
             "vec3 W=vec3(1.);"
             "float V=f(7.5*w+vec3(500.)+_time,6.,1.);"
             "i=mix(i,V*W,h);"
           "}"
         "}"
       "else"
         " if(k.m==1)"
           "{"
             "vec3 b=n+e*p,V=r(b),w=V*.5+.5;"
             "i=vec3(1.-f(5.*w,5.,1.))+vec3(.5,.4,.15);"
           "}"
       "gl_FragColor=vec4(i,1.);"
     "}"
 "}",

