/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\9_MountFuji\Shader\MountFuji_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter;"
 "uniform float _LeaveStartTime;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),sin(a),-sin(a),cos(a))\n"
 "#define dmin 0.0003\n"
 "#define tmax 100.0\n"
 "#define ln 128.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\n"
 "vec3 v;"
 "float m;struct mapr{float d;bool hit;int m;};"
 "void f(inout mapr v,float d,int y,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,y);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,y);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 t(vec3 v,vec3 m,vec3 d,vec3 y)"
 "{"
   "return v+=y,v.yz*=rot(m.x),v.xz*=rot(m.y),v.xy*=rot(m.z),v*=m,v;"
 "}"
 "float f(vec2 v)"
 "{"
   "uint m=floatBitsToUint(v.x*122.+v.y);"
   "m=m<<13U^m;"
   "m=m*(m*m*15731U+789221U)+1376312589U;"
   "return uintBitsToFloat(m>>9U|1065353216U)-1.;"
 "}"
 "float t(vec2 v)"
 "{"
   "return fract(sin(dot(v,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "float x(vec3 v)"
 "{"
   "return fract(sin(dot(v,vec3(12.9898,78.233,128.852)))*43758.5453123);"
 "}"
 "vec3 n(vec2 v)"
 "{"
   "vec2 m=floor(v),y=fract(v),z=y*y*(3.-2.*y);"
   "float d=f(m+vec2(0.,0.)),s=f(m+vec2(1.,0.)),x=f(m+vec2(0.,1.)),a=f(m+vec2(1.,1.)),i=mix(d,s,z.x),t=mix(x,a,z.x);"
   "return vec3(abs(mix(i,t,z.y)),6.*y*(1.-y)*(vec2(s-d,x-d)+(d-s-x+a)*z.yx));"
 "}"
 "float f(vec3 v)"
 "{"
   "return v=50.*fract(v*.3183099+vec3(.71,.113,.419)),-1.+2.*fract(v.x*v.y*v.z*(v.x+v.y+v.z));"
 "}"
 "vec4 p(vec3 v)"
 "{"
   "vec3 m=floor(v),y=fract(v),z=y*y*y*(y*(y*6.-15.)+10.),x=30.*y*y*(y*(y-2.)+1.);"
   "float d=f(m+vec3(0,0,0)),s=f(m+vec3(1,0,0)),t=f(m+vec3(0,1,0)),i=f(m+vec3(1,1,0)),e=f(m+vec3(0,0,1)),a=f(m+vec3(1,0,1)),r=f(m+vec3(0,1,1)),n=f(m+vec3(1,1,1)),c=d,l=s-d,w=t-d,U=e-d,b=d-s-t+i,p=d-t-e+r,o=d-s-e+a,u=-d+s+t-i+e-a-r+n;"
   "return vec4(-1.+2.*(c+l*z.x+w*z.y+U*z.z+b*z.x*z.y+p*z.y*z.z+o*z.z*z.x+u*z.x*z.y*z.z),2.*x*vec3(l+b*z.y+o*z.z+u*z.y*z.z,w+p*z.z+b*z.x+u*z.z*z.x,U+o*z.x+p*z.y+u*z.x*z.y));"
 "}"
 "const mat3 z=mat3(0.,.8,.6,-.8,.36,-.48,-.6,-.48,.64),y=mat3(0.,-.8,-.6,.8,.36,-.48,.6,-.48,.64);"
 "vec4 f(vec3 v,int d)"
 "{"
   "float m=1.9,t=.55,f=0.,r=.5;"
   "vec3 x=vec3(0.);"
   "mat3 e=mat3(1.,0.,0.,0.,1.,0.,0.,0.,1.);"
   "for(int i=0;i<d;i++)"
     "{"
       "vec4 n=p(v);"
       "f+=r*n.x;"
       "x+=r*e*n.yzw;"
       "r*=t;"
       "v=m*z*v;"
       "e=m*y*e;"
     "}"
   "f=f*.5+.5;"
   "return vec4(f,x);"
 "}"
 "vec3 r(vec2 v)"
 "{"
   "vec3 m=n(v+vec2(.5,1.));"
   "return vec3(pow(m.x,1.9),m.y,m.z);"
 "}"
 "float s(vec3 v)"
 "{"
   "float z=.24,y=1.,m=0.;"
   "vec2 d=v.xz*z+vec2(13.5,15.),x=vec2(0.);"
   "for(int f=0;f<7;f++)"
     "{"
       "vec3 n=r((d-x*.7)*z);"
       "m+=n.x*y;"
       "x+=n.yz*(n.x*2.-1.)*y;"
       "z*=2.5;"
       "y*=.58;"
       "y*=pow(n.x,.27);"
     "}"
   "m*=7./(1.+dot(v.xz,v.xz)*.01)+2./(1.+dot(v,v)*.001);"
   "m=min(m,8.5);"
   "return v.y-m;"
 "}"
 "mapr e(vec3 v)"
 "{"
   "mapr m;"
   "m.d=1e3;"
   "m.hit=false;"
   "m.m=-1;"
   "f(m,s(v),1,true);"
   "return m;"
 "}"
 "vec3 w(vec3 v)"
 "{"
   "vec2 z=vec2(.001,0.);"
   "return normalize(vec3(e(v+z.xyy).d-e(v-z.xyy).d,e(v+z.yxy).d-e(v-z.yxy).d,e(v+z.yyx).d-e(v-z.yyx).d));"
 "}"
 "vec2 e(vec3 v,int y,inout vec3 m)"
 "{"
   "float z=f(v*.5+vec3(-_time*.25,0.,0.),y).x;"
   "z=smoothstep(-.2,.6,z);"
   "float d=v.y-z*.1;"
   "m=vec3(0.,sign(v.y),0.);"
   "return vec2(d,z);"
 "}"
 "vec3 i(vec3 v)"
 "{"
   "v.y=max(v.y,0.);"
   "vec3 m;"
   "m.x=pow(1.-v.y,3.);"
   "m.y=pow(1.-v.y,1.2);"
   "m.z=.8+(1.-v.y)*.3;"
   "return m;"
 "}"
 "vec4 f(vec3 d,vec3 y,vec4 z)"
 "{"
   "float f=0.,x=0.,r=0.,t=0.;"
   "vec4 n=vec4(0.);"
   "for(;++r<ln;r++)"
     "{"
       "vec3 s=d+y*x,a;"
       "vec2 p=e(s,5,a);"
       "f=p.x;"
       "t=p.y;"
       "if(f>dmin)"
         "{"
           "vec4 u=vec4(vec3(mix(0.,1.,t)),t*1.2);"
           "u.w*=.4;"
           "u.xyz*=u.w;"
           "vec3 c=normalize(a);"
           "float w=clamp(dot(c,ldir),0.,1.);"
           "u.xyz*=w;"
           "n+=u*(1.-n.w)*clamp(1.3-s.y*.2,0.,1.);"
         "}"
       "x+=max(.05,.1*f);"
     "}"
   "n=max(vec4(0.),n);"
   "z.xyz=mix(z.xyz,n.xyz+vec3(.5),n.w);"
   "float a=1.-clamp(x/30.,0.,1.);"
   "z.xyz=mix(i(y),z.xyz,a);"
   "m=x;"
   "v=d+y*x;"
   "return z;"
 "}"
 "void main()"
 "{"
   "if(_RenderingTarget==2)"
     "gl_FragColor=vec4(vec3(0.),1.);"
   "else"
     "{"
       "vec2 v=uv*2.-1.;"
       "v.x*=_resolution.x/_resolution.y;"
       "vec3 d=_WorldCameraPos,z=_WorldCameraCenter;"
       "vec4 y=vec4(vec3(0.),1.);"
       "vec3 a=normalize(z-d),x=normalize(cross(vec3(0.,1.,0.),a)),t=normalize(cross(a,x)),s=normalize(v.x*x+v.y*t+a);"
       "float n=0.,r=0.;"
       "mapr p;"
       "for(;++n<ln;)"
         "{"
           "p=e(d+s*(r+=p.d));"
           "if(p.d<dmin)"
             "break;"
         "}"
       "if(p.hit)"
         "{"
           "if(p.m==0)"
             "y=vec4(vec3(exp(-.1*r)),1.);"
           "else"
             " if(p.m==1)"
               "{"
                 "vec3 u=d+s*r,c=w(u);"
                 "float l=1.-dot(c,vec3(0.,1.,0.)),U=mix(1.,l*l,clamp((u.y-5.)/5.,0.,1.));"
                 "vec3 o=mix(vec3(1.,1.,1.)*2.2,vec3(0.,0.,.1),smoothstep(0.,.35,U));"
                 "float b=max(.1,dot(ldir,c));"
                 "y.xyz=o*vec3(.5,.59,.75)*.6;"
                 "y.xyz+=vec3(0.,.04,.15)*U;"
                 "y.xyz+=vec3(1.,1.,.98)*b*min(1.,.111*exp2(u.y));"
                 "vec3 h=exp2(-.0025*r*vec3(1.,2.,4.));"
                 "y.xyz=mix(vec3(.5),y.xyz,h);"
               "}"
         "}"
       "else"
         " y.xyz=mix(y.xyz,i(s),step(dmin,p.d));"
       "vec4 c=f(d,s,y);"
       "float u=r,l=m*.55,U=clamp(u-l,0.,1.);"
       "y=mix(y,c,U);"
       "gl_FragColor=y;"
     "}"
 "}",

