/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\6_RoughMikado\Shader\EnergyTrail_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform sampler2D _BufferA;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "#define dmin 0.001\n"
 "#define tmax 1000.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\nstruct mapr{float d;bool hit;int m;float i;float tvalue;float acc;};"
 "void f(inout mapr v,float d,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,f,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,f,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 s(vec3 v,vec3 d,vec3 f,vec3 n)"
 "{"
   "return v+=n,v.yz*=rot(d.x),v.xz*=rot(d.y),v.xy*=rot(d.z),v*=d,v;"
 "}"
 "vec2 f(float v)"
 "{"
   "float d=sin(v*.11),f=cos(v*.14);"
   "return vec2(d*4.-f*1.5,f*1.7+d*1.5);"
 "}"
 "float s(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "float f(vec3 v,vec3 d)"
 "{"
   "return length(max(vec3(0.),abs(v)-d));"
 "}"
 "mapr v(vec3 v)"
 "{"
   "mapr d=mapr(1e3,false,-1,0.,0.,0.);"
   "for(float e=0.;e<20.;e++)"
     "{"
       "float a=.25+s(vec2(99.99,4545.21)*e)*1.25,y=s(vec2(6.621,1.11148)*e)*2.*3.1415,t=s(vec2(1.9987,.2259)*e)*2.*3.1415;"
       "vec3 n=vec3(a*cos(_time+y)*cos(_time+t),a*cos(_time+y)*sin(_time+t),a*sin(_time+y));"
       "f(d,length(v+n)-.001,0,true);"
     "}"
   "return d;"
 "}"
 "vec3 n(vec3 d)"
 "{"
   "vec2 n=vec2(.001,0.);"
   "return normalize(vec3(v(d+n.xyy).d-v(d-n.xyy).d,v(d+n.yxy).d-v(d-n.yxy).d,v(d+n.yyx).d-v(d-n.yyx).d));"
 "}"
 "mapr f(vec3 d,vec3 f,float n)"
 "{"
   "mapr m;"
   "float t=0.,e=0.,r=0.;"
   "for(;++t<n;)"
     "{"
       "m=v(d+f*(e+=m.d));"
       "if(m.d<dmin||m.tvalue>tmax)"
         "break;"
       "r+=exp(-15.*m.d);"
     "}"
   "m.i=t;"
   "m.tvalue=e;"
   "m.acc=r;"
   "return m;"
 "}"
 "vec3 n(mapr v,vec3 d,vec3 f,vec2 n)"
 "{"
   "vec3 t=vec3(.125,.291,.723)*v.acc*2.;"
   "return t;"
 "}"
 "void main()"
 "{"
   "vec2 v=uv*2.-1.;"
   "v.x*=_resolution.x/_resolution.y;"
   "vec3 d=vec3(cos(_time),0.,sin(_time)),a=vec3(0.,0.,0.),e=normalize(a-d),t=normalize(cross(vec3(0.,1.,0.),e)),c=normalize(cross(e,t)),r=normalize(v.x*t+v.y*c+e),i=vec3(0.);"
   "mapr m=f(d,r,64.);"
   "i=n(m,d,r,v);"
   "i=mix(i,texture(_BufferA,uv).xyz,.981);"
   "gl_FragColor=vec4(i,1.);"
 "}",

