/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\6_RoughMikado\Shader\EnergyField_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter;"
 "uniform sampler2D _BufferA;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "#define dmin 0.001\n"
 "#define tmax 30.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\n"
 "vec3 v;"
 "int m;"
 "float f;struct mapr{float d;bool hit;int m;float tvalue;float i;};"
 "void t(inout mapr v,float m,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(m<v.d)"
         "v=mapr(m,false,f,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(m>v.d)"
         "v=mapr(m,false,f,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 x(vec3 v,vec3 m,vec3 f,vec3 z)"
 "{"
   "return v+=z,v.yz*=rot(m.x),v.xz*=rot(m.y),v.xy*=rot(m.z),v*=m,v;"
 "}"
 "float t(vec3 v)"
 "{"
   "return v=50.*fract(v*.3183099+vec3(.71,.113,.419)),-1.+2.*fract(v.x*v.y*v.z*(v.x+v.y+v.z));"
 "}"
 "vec4 x(vec3 v)"
 "{"
   "vec3 m=floor(v),f=fract(v),s=f*f*f*(f*(f*6.-15.)+10.),y=30.*f*f*(f*(f-2.)+1.);"
   "float z=t(m+vec3(0,0,0)),x=t(m+vec3(1,0,0)),n=t(m+vec3(0,1,0)),e=t(m+vec3(1,1,0)),d=t(m+vec3(0,0,1)),i=t(m+vec3(1,0,1)),r=t(m+vec3(0,1,1)),k=t(m+vec3(1,1,1)),a=z,c=x-z,l=n-z,u=d-z,p=z-x-n+e,b=z-n-d+r,o=z-x-d+i,w=-z+x+n-e+d-i-r+k;"
   "return vec4(-1.+2.*(a+c*s.x+l*s.y+u*s.z+p*s.x*s.y+b*s.y*s.z+o*s.z*s.x+w*s.x*s.y*s.z),2.*y*vec3(c+p*s.y+o*s.z+w*s.y*s.z,l+b*s.z+p*s.x+w*s.z*s.x,u+o*s.x+b*s.y+w*s.x*s.y));"
 "}"
 "const mat3 y=mat3(0.,.8,.6,-.8,.36,-.48,-.6,-.48,.64),e=mat3(0.,-.8,-.6,.8,.36,-.48,.6,-.48,.64);"
 "vec4 t(vec3 v,int m)"
 "{"
   "float f=1.9,t=.55,z=0.,r=.5;"
   "vec3 i=vec3(0.);"
   "mat3 s=mat3(1.,0.,0.,0.,1.,0.,0.,0.,1.);"
   "for(int d=0;d<m;d++)"
     "{"
       "vec4 n=x(v);"
       "z+=r*n.x;"
       "i+=r*s*n.yzw;"
       "r*=t;"
       "v=f*y*v;"
       "s=f*e*s;"
     "}"
   "z=z*.5+.5;"
   "return vec4(z,i);"
 "}"
 "float x(vec3 v,float m)"
 "{"
   "const vec3 s=vec3(1.,100.,1e3);"
   "v*=m;"
   "vec3 f=floor(mod(v,m))*s,n=floor(mod(v+vec3(1.),m))*s,z=fract(v);"
   "z=z*z*(3.-2.*z);"
   "vec4 y=vec4(f.x+f.y+f.z,n.x+f.y+f.z,f.x+n.y+f.z,n.x+n.y+f.z),i=fract(sin(y*.1)*1e3);"
   "float a=mix(mix(i.x,i.y,z.x),mix(i.z,i.w,z.x),z.y);"
   "i=fract(sin((y+n.z-f.z)*.1)*1e3);"
   "float e=mix(mix(i.x,i.y,z.x),mix(i.z,i.w,z.x),z.y);"
   "return mix(a,e,z.z)*2.-1.;"
 "}"
 "float s(vec3 v,float s)"
 "{"
   "float m=0.;"
   "for(int f=0;f<7;f++)"
     "{"
       "float z=pow(2.,float(f));"
       "m+=1.5/z*x(v+vec3(1.)*(float(f)/17.),z*s);"
     "}"
   "return clamp((1.-m)*.5,0.,1.)*2.;"
 "}"
 "vec2 r(vec3 v,int m)"
 "{"
   "float f=t(v*.5+vec3(-_time*.25,0.,0.),m).x;"
   "f=smoothstep(-.2,.6,f);"
   "float z=v.y-f*.1;"
   "return vec2(z,f);"
 "}"
 "mapr r(vec3 v)"
 "{"
   "mapr m=mapr(1e3,false,-1,0.,0.);"
   "{"
     "float f=t(v,9).x;"
     "t(m,v.y+1.+f,1,true);"
   "}"
   "return m;"
 "}"
 "mapr n(vec3 v,vec3 f)"
 "{"
   "mapr m;"
   "float z=0.,i=0.,y=0.;"
   "for(;++z<64.;)"
     "{"
       "m=r(v+f*(i+=m.d*.75));"
       "if(m.d<.001)"
         "{"
           "m.hit=true;"
           "break;"
         "}"
       "if(m.d>1e3)"
         "break;"
       "y+=exp(-3.*m.d);"
     "}"
   "m.i=z;"
   "m.tvalue=i;"
   "return m;"
 "}"
 "vec3 n(vec3 v)"
 "{"
   "vec2 f=vec2(.001,0.);"
   "return normalize(vec3(r(v+f.xyy).d-r(v-f.xyy).d,r(v+f.yxy).d-r(v-f.yxy).d,r(v+f.yyx).d-r(v-f.yyx).d));"
 "}"
 "vec4 s(vec2 v)"
 "{"
   "float m=_resolution.y/_resolution.x;"
   "v.y*=m;"
   "vec4 f=vec4(.125,.291,.723,1.),z=vec4(.925,.791,.323,1.);"
   "float i=7.f;"
   "vec2 y=vec2(.5,.5*m);"
   "float a=1.-distance(v,y)*2.,e=pow(a,3.5);"
   "vec2 t=-normalize(v-y)*.4;"
   "float x=fract(_time*.3+.5),n=fract(_time*.3);"
   "vec2 r=v+x*t,d=v+n*t;"
   "float c=e*sin(_time*.9)*1.2,u=cos(c),l=sin(c);"
   "mat2 k;"
   "k[0]=vec2(u,-l);"
   "k[1]=vec2(l,u);"
   "r=y+(r-y)*k;"
   "d=y+(d-y)*k;"
   "float w=max(s(vec3(r,1.),i),s(vec3(r,1.)*1.2,i)),p=max(s(vec3(d,1.),i),s(vec3(d,1.)*1.4,i)),b=abs((.5-x)/.5),o=mix(w,p,b);"
   "vec4 h=vec4(o,o,o,1.)*mix(f,z,e)*e;"
   "h+=pow(a,16.)*mix(f,z,pow(a,16.))*2.3;"
   "h=max(vec4(0.),h);"
   "return h;"
 "}"
 "vec3 n(mapr v,vec3 m,vec3 f)"
 "{"
   "vec3 i=vec3(0.);"
   "if(v.hit)"
     "if(v.m==0)"
       "i=vec3(1.)*exp(-1.*v.tvalue);"
     "else"
       " if(v.m==1)"
         "{"
           "vec3 a=m+f*v.tvalue,z=n(a);"
           "float y=max(0.,dot(z,ldir)),s=pow(max(0.,dot(reflect(-ldir,z),-f)),16.);"
           "i=vec3(.1)*(y+.1)+vec3(1.)*s;"
         "}"
   "return i;"
 "}"
 "void main()"
 "{"
   "vec2 v=uv*2.-1.;"
   "v.x*=_resolution.x/_resolution.y;"
   "vec3 m=vec3(cos(_time),0.,sin(_time)),i=vec3(0.,0.,0.),z=normalize(i-m),y=normalize(cross(vec3(0.,1.,0.),z)),e=normalize(cross(z,y)),d=normalize(v.x*y+v.y*e+z),r=vec3(0.);"
   "f=16.;"
   "mapr a;"
   "a=n(m,d);"
   "r=n(a,m,d);"
   "vec3 x=mix(vec3(.1),vec3(.85),-d.y*.5+.5)*.25;"
   "r=mix(r,x*sqrt(x)*1.2,smoothstep(0.,.95,a.tvalue/10.));"
   "r+=s(uv).xyz;"
   "r+=texture(_BufferA,uv).xyz;"
   "gl_FragColor=vec4(r,1.);"
 "}",

