/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\7_FeatherRobe\Shader\FeatherRobeTrail_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter;"
 "uniform sampler2D _BufferA;"
 "in vec2 uv;\n"
 "#define pi 3.14159265\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "#define dmin 0.001\n"
 "#define tmax 1000.0\n"
 "#define ldir normalize(vec3(1.0,1.0,-1.0))\nstruct mapr{float d;bool hit;int m;float i;float tvalue;float acc;};"
 "void f(inout mapr v,float d,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,f,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,f,0.,0.,0.);"
       "if(v.d<dmin)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 s(vec3 v,vec3 d,vec3 f,vec3 n)"
 "{"
   "return v+=n,v.yz*=rot(d.x),v.xz*=rot(d.y),v.xy*=rot(d.z),v*=d,v;"
 "}"
 "vec2 f(float v)"
 "{"
   "float d=sin(v*.11),f=cos(v*.14);"
   "return vec2(d*4.-f*1.5,f*1.7+d*1.5);"
 "}"
 "float s(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "float f(vec3 v,vec3 d)"
 "{"
   "return length(max(vec3(0.),abs(v)-d));"
 "}"
 "mapr v(vec3 v)"
 "{"
   "mapr d=mapr(1e3,false,-1,0.,0.,0.);"
   "for(float r=0.;r<20.;r++)"
     "{"
       "float e=.25+s(vec2(99.99,4545.21)*5.)*1.25,c=1.,a=.1*r,t=s(vec2(6.621,1.11148)*5.)*2.*3.1415,i=s(vec2(1.9987,.2259)*5.)*2.*3.1415;"
       "vec3 n=vec3(4.*e*cos(_time*c+t-a)*cos(_time*c+i-a),4.*e*cos(_time*c+t-a)*sin(_time*c+i-a),4.*e*sin(_time*c+t-a)),y=vec3(0.,2.,0.)+n;"
       "f(d,length(v+y)-.005,0,true);"
     "}"
   "return d;"
 "}"
 "vec3 n(vec3 d)"
 "{"
   "vec2 n=vec2(.001,0.);"
   "return normalize(vec3(v(d+n.xyy).d-v(d-n.xyy).d,v(d+n.yxy).d-v(d-n.yxy).d,v(d+n.yyx).d-v(d-n.yyx).d));"
 "}"
 "mapr f(vec3 d,vec3 f,float a)"
 "{"
   "mapr n;"
   "float t=0.,c=0.,r=0.;"
   "for(;++t<a;)"
     "{"
       "n=v(d+f*(c+=n.d));"
       "if(n.d<dmin||n.tvalue>tmax)"
         "break;"
       "r+=exp(-15.*n.d);"
     "}"
   "n.i=t;"
   "n.tvalue=c;"
   "n.acc=r;"
   "return n;"
 "}"
 "vec3 n(mapr n,vec3 d,vec3 v,vec2 a)"
 "{"
   "vec3 t=vec3(.917,.569,.596)*n.acc*2.;"
   "return t;"
 "}"
 "void main()"
 "{"
   "vec2 v=uv*2.-1.;"
   "v.x*=_resolution.x/_resolution.y;"
   "vec3 d=_WorldCameraPos,t=_WorldCameraCenter,a=normalize(t-d),c=normalize(cross(vec3(0.,1.,0.),a)),r=normalize(cross(a,c)),e=normalize(v.x*c+v.y*r+a),i=vec3(0.);"
   "mapr m=f(d,e,64.);"
   "i=n(m,d,e,v);"
   "i=mix(i,texture(_BufferA,uv).xyz,.981);"
   "gl_FragColor=vec4(i,1.);"
 "}",

