/* File generated with Shader Minifier 1.3.1
 * http://www.ctrl-alt-test.fr
 */

// E:\CppDev\GradDemo\Haru86_GraphicsEngine\Assets\App\GradDemo\7_FeatherRobe\Shader\FeatherRobe_Frag.h
"#version 330\n"
 "uniform float _time;"
 "uniform vec2 _resolution;"
 "uniform float _RenderingTarget;"
 "uniform vec3 _WorldCameraPos,_WorldCameraCenter,_AuraPos;"
 "uniform sampler2D _BufferA;"
 "uniform float _Alpha;"
 "in vec2 uv;"
 "const float v=3.14159265;\n"
 "#define rot(a)mat2(cos(a),-sin(a),sin(a),cos(a))\n"
 "const float y=3e-4,c=30.;"
 "const vec3 f=normalize(vec3(1.,1.,-1.));"
 "vec3 e;"
 "int m;"
 "float i;struct mapr{float d;bool hit;int m;float tv;float i;float acc;float neard;};"
 "void t(inout mapr v,float d,int f,bool a)"
 "{"
   "if(a)"
     "{"
       "if(d<v.d)"
         "v=mapr(d,false,f,0.,0.,0.,0.);"
       "if(v.d<y)"
         "v.hit=true;"
     "}"
   "else"
     "{"
       "if(d>v.d)"
         "v=mapr(d,false,f,0.,0.,0.,0.);"
       "if(v.d<y)"
         "v.hit=true;"
     "}"
 "}"
 "vec3 n(vec3 v,vec3 d,vec3 f,vec3 y)"
 "{"
   "return v+=y,v.yz*=rot(d.x),v.xz*=rot(d.y),v.xy*=rot(d.z),v*=d,v;"
 "}"
 "vec3 n(vec3 v,vec3 y)"
 "{"
   "vec3 f=vec3(0.,0.,_time)+y;"
   "return f;"
 "}"
 "float n(vec2 v)"
 "{"
   "return fract(sin(dot(v.xy,vec2(12.9898,78.233)))*43758.5453123);"
 "}"
 "const int d=50;"
 "const float a=.001,o=1.;"
 "vec2 n(vec2 v,vec2 d,vec2 y)"
 "{"
   "vec2 f=y-v,c=d-v;"
   "float a=clamp(dot(f,c)/dot(c,c),0.,1.);"
   "return vec2(dot(f-c*a,f-c*a),f.x*c.y-f.y*c.x);"
 "}"
 "float s(vec2 v,vec2 f,vec2 d,vec2 y)"
 "{"
   "vec2 c=min(min(n(v,f,y),n(f,d,y)),n(d,v,y));"
   "return-sqrt(c.x)*sign(c.y);"
 "}"
 "vec3 s(vec2 v,float y)"
 "{"
   "vec2 f=vec2(-.12,.1),c=vec2(.12,.1),d=vec2(0.,.4);"
   "float a=y*.1,i=min(1.,300.*s(c+vec2(a,-a),f+vec2(-a,-a),d+vec2(0.,a),v));"
   "if(i<0.)"
     "i=pow(smoothstep(0.,1.,abs(i*.05)),.1);"
   "i=max(.6,i);"
   "return vec3(i)*vec3(1.,.95,.975);"
 "}"
 "int n(const vec3 v,const vec3 d,const vec3 f,const vec3 m,const vec3 c,out float y)"
 "{"
   "vec3 i,r,x,t,e;"
   "float s,u,o,p,n;"
   "i=d-v;"
   "r=f-v;"
   "x=cross(c,r);"
   "s=dot(i,x);"
   "if(s>-a&&s<a)"
     "return 0;"
   "u=1./s;"
   "e=m-v;"
   "o=dot(e,x)*u;"
   "if(o<0.||o>1.)"
     "return 0;"
   "t=cross(e,i);"
   "p=dot(c,t)*u;"
   "if(p<0.||o+p>1.)"
     "return 0;"
   "n=dot(r,t)*u;"
   "if(n>a)"
     "return y=n,1;"
   "return 0;"
 "}"
 "int s(const vec3 v,const vec3 d,const vec3 f,const vec3 m,const vec3 c,out float y)"
 "{"
   "vec3 i,r,x,t,e;"
   "float s,u,o,n,p;"
   "i=d-v;"
   "r=f-v;"
   "x=cross(c,r);"
   "s=dot(i,x);"
   "if(s>-a&&s<a)"
     "return 0;"
   "u=1./s;"
   "e=m-v;"
   "o=dot(e,x)*u;"
   "t=cross(e,i);"
   "n=dot(c,t)*u;"
   "p=dot(r,t)*u;"
   "if(p>a)"
     "return y=p,1;"
   "return 0;"
 "}"
 "vec3 s(vec3 v,float d,float y)"
 "{"
   "float f=1.;"
   "v.z+=d;"
   "vec2 c=floor(v.xz),a=c+vec2(f,f);"
   "float i=.002,t=20.,e=5.,r=_time;"
   "r=1.;"
   "float m=sin(e*r+t*n(i*c)),x=sin(e*r+t*n(i*vec2(a.x,c.y))),o=sin(e*r+t*n(i*a)),u=sin(e*r+t*n(i*vec2(c.x,a.y))),p=.7*max(.3,min(1.,-(c.y-26.)*.05));"
   "vec3 l=vec3(c.x,m*p,c.y),z=vec3(a.x,x*p,c.y),b=vec3(a.x,o*p,a.y),A=vec3(c.x,u*p,a.y);"
   "float k,h,g,C;"
   "vec3 w=v+vec3(0.,100.,0.),W=vec3(0.,-1.,0.);"
   "int P=n(l,z,b,w,W,k),T=s(l,b,A,w,W,h);"
   "if(P==1&&T>0)"
     "{"
       "vec3 R=w+W*k;"
       "return R;"
     "}"
   "vec3 R=w+W*h;"
   "return R;"
 "}"
 "mapr s(vec3 v)"
 "{"
   "mapr f;"
   "f.d=1e3;"
   "f.hit=false;"
   "f.m=-1;"
   "t(f,v.y-s(v,0.,1.).y*.75+3.,1,true);"
   "return f;"
 "}"
 "vec3 t(vec3 v)"
 "{"
   "vec2 f=vec2(.001,0.);"
   "return normalize(vec3(s(v+f.xyy).d-s(v-f.xyy).d,s(v+f.yxy).d-s(v-f.yxy).d,s(v+f.yyx).d-s(v-f.yyx).d));"
 "}"
 "mapr t(vec3 v,vec3 f,const bool a)"
 "{"
   "mapr d;"
   "float m=0.,e=0.,r=0.;"
   "for(;++m<i;)"
     "{"
       "d=s(v+f*(e+=d.d*.75));"
       "if(d.d<y||d.tv>c)"
         "break;"
       "r+=exp(-3.*d.d);"
     "}"
   "d.i=m;"
   "d.tv=e;"
   "d.acc=r;"
   "return d;"
 "}"
 "mapr t(vec3 v,vec3 y)"
 "{"
   "mapr f;"
   "f.neard=1e3;"
   "float c=.25+n(vec2(99.99,4545.21)*5.)*1.25,r=1.,a=n(vec2(6.621,1.11148)*5.)*2.*3.1415,t=n(vec2(1.9987,.2259)*5.)*2.*3.1415;"
   "vec3 d=vec3(4.*c*cos(_time*r+a)*cos(_time*r+t),4.*c*cos(_time*r+a)*sin(_time*r+t),4.*c*sin(_time*r+a)),x=vec3(0.,2.,0.)+d;"
   "float m=0.,e=0.,i=0.;"
   "for(;++m<64.;)"
     "{"
       "f=mapr(length(v+y*(e+=f.d*.75)+x)-.25,false,2,0.,0.,0.,0.);"
       "if(f.d<f.neard)"
         "f.neard=f.d;"
       "if(f.d<.001)"
         "{"
           "f.hit=true;"
           "break;"
         "}"
       "if(f.d>1e3)"
         "break;"
       "i+=exp(-3.*f.d);"
     "}"
   "f.i=m;"
   "f.tv=e;"
   "f.acc=i;"
   "return f;"
 "}"
 "float r(vec3 v,vec3 f,float y)"
 "{"
   "return(-v.z+y)/f.z;"
 "}"
 "vec3 n(vec3 v,vec3 f,vec3 y,vec3 d,vec3 c,float m,float a)"
 "{"
   "vec3 i=normalize(reflect(c,y)),x=normalize(f-v);"
   "float t=dot(i,x),e=max(0.,t);"
   "vec3 o=vec3(e+.7),p=normalize(reflect(-x,d));"
   "float u=r(f,p,10.);"
   "vec3 n=f+p*u;"
   "float R=max(0.,t*2.);"
   "vec3 W=s(abs(n.xy)*vec2(.1,-.2)+vec2(0.,2.),a);"
   "return o*R+W*(1.-R);"
 "}"
 "float r(vec3 v,vec3 y)"
 "{"
   "float f=1.,r=0.;"
   "for(int i=0;i<5;i++)"
     "{"
       "float c=.15+float(i)*.15,a=s(y*c+v).d;"
       "r+=(c-a)*f;"
       "f*=.5;"
     "}"
   "return clamp(1.-r,0.,1.);"
 "}"
 "vec3 p(vec3 v,vec3 f,vec2 y)"
 "{"
   "vec3 d=vec3(.2,.2,.5)*.1;"
   "return d;"
 "}"
 "vec3 p(mapr v,vec3 d,vec3 y,vec2 a)"
 "{"
   "vec3 i=vec3(0.);"
   "if(v.hit)"
     "{"
       "vec3 c=d+y*v.tv,r=t(c),x=normalize(r+vec3(0.,8.,0.));"
       "if(v.m==1)"
         "{"
           "vec3 m=vec3(1.,.95,.9);"
           "float e=abs(mod(c.x,1.)),p=abs(mod(c.z,1.)),o=60.,u=pow(e,o)+pow(1.-e,o)+pow(p,o)+pow(1.-p,o)+pow(1.-abs(e-p),o);"
           "u=max(0.,min(1.,u));"
           "vec3 s=n(d,c,r,x,f,-1.,1.)*m+u*4.*vec3(.917,.569,.596);"
           "i=vec3(exp(-.25*v.tv));"
           "float R=1.-length(a-vec2(0.,.25))*.5,z=max(0.,dot(r,f)),k=pow(max(0.,dot(reflect(-f,r),-y)),16.);"
           "i=vec3(.2,.2,.5)*.1*s*(z+.25)+vec3(1.)*k;"
           "i+=vec3(1.)*v.acc*.01;"
           "i*=R;"
         "}"
     "}"
   "return i;"
 "}"
 "void main()"
 "{"
   "if(_RenderingTarget==2)"
     "gl_FragColor=vec4(vec3(0.),1.);"
   "else"
     "{"
       "vec2 v=uv*2.-1.;"
       "v.x*=_resolution.x/_resolution.y;"
       "vec3 f=_WorldCameraPos,c=_WorldCameraCenter,a=normalize(c-f),r=normalize(cross(vec3(0.,1.,0.),a)),o=normalize(cross(a,r)),d=normalize(v.x*r+v.y*o+a),e=p(f,d,v);"
       "i=128.;"
       "mapr m;"
       "m=t(f,d,false);"
       "if(m.hit)"
         "e=p(m,f,d,v);"
       "vec3 y=mix(vec3(.96),vec3(.24),-d.y*.5+.5);"
       "e=mix(e,y*sqrt(y)*1.2,smoothstep(0.,.95,m.tv/15.));"
       "mapr u=t(f,d);"
       "vec3 n=vec3(.917,.569,.596)*u.acc;"
       "e+=n;"
       "e+=texture(_BufferA,uv).xyz;"
       "gl_FragColor=vec4(e,_Alpha);"
     "}"
 "}",

